### ISSUE TITLE
Discussion on future of `iceoryx_ros2_bridge`

### ISSUE THREAD

**Issue by mossmaurice** [ros2/rmw_iceoryx#56]
@budrus and myself were discussing the `iceoryx_ros2_bridge` today. We came to the conclusion that it's most likely not needed anymore because if one wants to interface with DDS there are two other options which are now available:

1) Use [rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds) and activate [shared memory transmission](https://github.com/ros2/rmw_cyclonedds/blob/master/shared_memory_support.md) via iceoryx
2) Use the rmw_iceoryx and run the [Cyclone DDS gateway/bridge](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_dds/README.md)

@ZhenshengLee Would that fit the use-case of Bright Dream Robotics?

@Karsten1987 @jeising @JanStaschulat What do you think? Would that be ok from Bosch-side?

**Comment by ZhenshengLee** [comment]
@mossmaurice
I think `iceoryx_ros2_bridge` is designed for connecting rmw_iceoryx based nodes to another nodes with any dds implementation, that means it should work in the layer of rmw rather than one of ddses.

> * Use [rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds) and activate [shared memory transmission](https://github.com/ros2/rmw_cyclonedds/blob/master/shared_memory_support.md) via iceoryx
> * Use the rmw_iceoryx and run the [Cyclone DDS gateway/bridge](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_dds/README.md)

These two methods do the work of `iceoryx_cyclonedds_bridge`.

Currently `iceoryx_fastdds_bridge` is needed to connect rmw_iceoryx to microROS, which is based on [rmw_microxrcedds](https://github.com/micro-ROS/rmw-microxrcedds).

Zenoh project has a plan to replace microxrcedds in microROS because it can be deployed in resource-constrained devices like microcontroller, see [ros discource](https://discourse.ros.org/t/intro-brandon-from-opencv-ai-kit/16011/2), but as https://github.com/eclipse-zenoh/zenoh/issues/118 said, zenoh will not replace microxrcedds in the context of serial link.

**Comment by ZhenshengLee** [comment]
@mossmaurice 

> Currently `iceoryx_fastdds_bridge` is needed to connect rmw_iceoryx to microROS, which is based on [rmw_microxrcedds](https://github.com/micro-ROS/rmw-microxrcedds).

According to https://github.com/eclipse-iceoryx/iceoryx/pull/444 FastDDS gateway/bridge is on its way.

I believe more dds will be added too.

> 2\. Use the rmw_iceoryx and run the [Cyclone DDS gateway/bridge](https://github.com/eclipse-iceoryx/iceoryx/blob/master/iceoryx_dds/README.md)

So this method may work in cases of my company, `iceoryx_ros2_bridge` shall be deleted.

Thanks.

**Comment by ZhenshengLee** [comment]
> According to eclipse-iceoryx/iceoryx#444 FastDDS gateway/bridge is on its way.

AFAK, this commit eclipse-iceoryx/iceoryx#444 has been abort.
