### ISSUE TITLE
Question: will rmw_iceoryx reduce the time of publish()?

### ISSUE THREAD

**Issue by felixf4xu** [ros2/rmw_iceoryx#95]
Hi,

I'm currently using `RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` and in my code below
```c++
  sensor_msgs::msg::PointCloud2 map_msg;
  pcl::toROSMsg(*map_pcl, map_msg);
  ndt_map_pub->publish(map_msg); //ros2 topic bw /ndt_map: 125.35MB
```
the function of `publish` costs about 139,394 us, which is unacceptably slow.

I'd like to check if I switch to [rmw_iceoryx](https://github.com/ros2/rmw_iceoryx), because of the zero-copy design, will the function of `publish` cost less time?

**Comment by mossmaurice** [comment]
@felixf4xu Thanks, for raising this question!

In order for messages to be zero-copyable they need to have a fixed-sized otherwise iceoryx does not know how much memory to allocate in the shared memory area.

> the function of publish costs about 139,394 us, which is unacceptably slow.

What you are seeing here is the simple, straightforward serialization implemented in `rmw_iceoryx`. It takes some time because the publisher needs to serialize the message and the subscriber needs to deserialize.

To make full use of zero-copy, what you would need to do in your project, is to change all messages to be fixed-size. For example, have a look at [this repository](https://github.com/ZhenshengLee/ros2_shm_msgs). Here you can see different point cloud message types [defined](https://github.com/ZhenshengLee/ros2_shm_msgs/tree/humble/msg). The caveat with such an approach is that the compatibility between the message types breaks and you need some conversion method.

**Comment by mossmaurice** [comment]
@felixf4xu Closing this issue. If you have more questions, feel free to re-open this issue.
